name: Bug Report
description: File a bug report to help us improve
title: "[Bug]: "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible.

  - type: checkboxes
    id: pre-checks
    attributes:
      label: Pre-submission Checks
      description: Please confirm you have completed these steps
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have read the documentation
          required: true
        - label: I am using a supported version of Node.js (18.x, 20.x, or 22.x)
          required: true
        - label: I am using a supported version of Electron (25.x or higher)
          required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the issue you're experiencing...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the behavior
      placeholder: |
        1. Initialize ApiKeyServiceMain with...
        2. Call method...
        3. Observe error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear description of what you expected to happen
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: A clear description of what actually happened
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - Windows 10
        - Windows 11
        - macOS 11 (Big Sur)
        - macOS 12 (Monterey)
        - macOS 13 (Ventura)
        - macOS 14 (Sonoma)
        - Ubuntu 20.04
        - Ubuntu 22.04
        - Other Linux (specify in additional context)
    validations:
      required: true

  - type: dropdown
    id: node-version
    attributes:
      label: Node.js Version
      description: What version of Node.js are you using?
      options:
        - 18.x (LTS)
        - 20.x (LTS)
        - 22.x (Current)
        - Other (specify in additional context)
    validations:
      required: true

  - type: dropdown
    id: electron-version
    attributes:
      label: Electron Version
      description: What version of Electron are you using?
      options:
        - 25.x
        - 26.x
        - 27.x
        - 28.x
        - 29.x
        - 30.x
        - Other (specify in additional context)
    validations:
      required: true

  - type: input
    id: package-version
    attributes:
      label: Package Version
      description: What version of genai-key-storage-lite are you using?
      placeholder: "0.1.0"
    validations:
      required: true

  - type: textarea
    id: error-logs
    attributes:
      label: Error Logs
      description: |
        Please include any relevant error logs or stack traces.
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
      render: shell
    validations:
      required: false

  - type: textarea
    id: code-sample
    attributes:
      label: Code Sample
      description: Please provide a minimal code sample that reproduces the issue
      render: typescript
      placeholder: |
        import { ApiKeyServiceMain } from 'genai-key-storage-lite';
        
        // Minimal code that reproduces the issue
        const service = new ApiKeyServiceMain('/path/to/user/data');
        // ...
    validations:
      required: false

  - type: dropdown
    id: security-sensitive
    attributes:
      label: Security Sensitivity
      description: Does this bug involve security-sensitive functionality?
      options:
        - "No - General functionality bug"
        - "Yes - Involves API key storage/encryption"
        - "Yes - Involves file system security"
        - "Yes - Other security concern"
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: |
        Add any other context about the problem here.
        Include details about your Electron app setup, any custom configurations, etc.
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be willing to help fix this issue?
      options:
        - label: I would be willing to submit a pull request to fix this issue
          required: false